//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spor_Salonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurulars
    {
        public int Id { get; set; }
        public string duyuru_adi { get; set; }
        public string duyuru_konu { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
