//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spor_Salonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyelers
    {
        public int Id { get; set; }
        public string uye_adisoyadi { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public System.DateTime uyelik_baslangic_tarihi { get; set; }
        public System.DateTime uyelik_bitis_tarihi { get; set; }
        public int toplam_ucret { get; set; }
        public int odenen_ucret { get; set; }
        public int kalan_ucret { get; set; }
    }
}
