//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spor_Salonu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class veritabaniEntities : DbContext
    {
        public veritabaniEntities()
            : base("name=veritabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Duyurulars> Duyurulars { get; set; }
        public virtual DbSet<Kayits> Kayits { get; set; }
        public virtual DbSet<Mesajs> Mesajs { get; set; }
        public virtual DbSet<Uyelers> Uyelers { get; set; }
        public virtual DbSet<Mesailer> Mesailer { get; set; }
    }
}
